<?php
declare(strict_types=1);

namespace App\Modules\Base\Entity;

use App\Modules\Base\Casts\MetaCast;
use App\Modules\Page\Entity\WidgetData;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

/**
 * Родительский класс для публикуемых классов, которые имеют свою страницу и могут быть добавлены в меню и каталоги
 * @property int $id
 * @property string $name
 * @property string $slug
 * @property string $awesome
 * @property Meta $meta
 * @property bool $active
 * @property Carbon $created_at
 * @property Carbon $updated_at
 * @property Carbon $activated_at
 * @property Photo $image
 * @property Photo $icon
 *
 */
abstract class DisplayedModel extends Model implements DisplayedData
{

    //Employee ??? + Widget
    // * Specialization + Widget
    // * Service + Widget
    // * Classification + Widget
    //Page
    //Post + Widge

    /// На будущее - Товары, Каталог

    public function __construct(array $attributes = [])
    {
        //Объединяем базовые параметры
        parent::__construct($attributes);

        $casts = [
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
            'activated_at' => 'datetime',
            'meta' => MetaCast::class,
        ];
        $fillable = [
            'name',
            'slug',
            'active',
        ];
        $attributes = [
            'meta' => '{}',
        ];

        $this->casts = array_merge($this->casts, $casts);
        $this->fillable = array_merge($this->fillable, $fillable);
        $this->attributes = array_merge($this->attributes, $attributes);

    }

    public static function register(string $name, string $slug = ''): self
    {
        $model = static::make([
            'name' => $name,
            'active' => false,
        ]);
        $model->setSlug($slug);
        $model->save();
        return $model;
    }

    /**
     * Функции состояния
     */

    public function isActive(): bool
    {
        return $this->active == true;
    }

    /**
     * Сетеры
     */

    public function setSlug(string $slug = ''): void
    {
        $this->slug = empty($slug) ? Str::slug($this->name) : $slug;
    }

    public function draft()
    {
        $this->active = false;
        $this->save();
    }

    public function activated()
    {
        if (is_null($this->activated_at)) $this->activated_at = now();
        $this->active = true;
        $this->save();
    }

    public function saveImage($file, bool $clear_current = false): void
    {
        if ($clear_current && (!is_null($this->image) || !is_null($this->image->file)))
            $this->image->delete();

        if (empty($file)) return;
        $this->image->newUploadFile($file, 'image');
    }

    public function saveIcon($file, bool $clear_current = false): void
    {
        if ($clear_current && (!is_null($this->icon) || !is_null($this->icon->file)))
            $this->icon->delete();

        if (empty($file)) return;
        $this->icon->newUploadFile($file, 'icon');
    }

    /**
     * Гетеры
     */

    public function getActivatedAt(): string
    {
        return is_null($this->activated_at) ? '' : $this->activated_at->translatedFormat('d F Y');
    }

    public function getImage(string $thumb = ''): ?string
    {
        if (is_null($this->image) || is_null($this->image->file)) return null;
        if (empty($thumb)) return $this->image->getUploadUrl();
        return $this->image->getThumbUrl($thumb);
    }

    public function getIcon(string $thumb = ''): ?string
    {
        if (is_null($this->icon) || is_null($this->icon->file)) return null;
        if (empty($thumb)) return $this->icon->getUploadUrl();
        return $this->icon->getThumbUrl($thumb);
    }

    public function getAwesome(): string
    {
        if (is_null($this->awesome)) return '';

        return '<i class="' . $this->awesome . '"></i>';
    }
    /**
     * Отношения
     */
    public function image()
    {
        return $this->morphOne(Photo::class, 'imageable')->where('type','image')->withDefault();
    }

    public function icon()
    {
        return $this->morphOne(Photo::class, 'imageable')->where('type', 'icon')->withDefault();
    }


    public function scopeActive($query)
    {
        return $query->where('active', true);
    }

    /*public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function (Model $model) {
            $casts = [
                'created_at' => 'datetime',
                'updated_at' => 'datetime',
                'activated_at' => 'datetime',
                'meta' => MetaCast::class,
            ];
            $fillable = [
                'name',
                'slug',
                'active',
            ];
            $attributes = [
                'meta' => '{}',
            ];

            $model->casts = array_merge($model->casts, $casts);
            $model->fillable = array_merge($model->fillable, $fillable);
            $model->attributes = array_merge($model->attributes, $attributes);

        });
    }*/
}
